title:             Square Zero
email:             sssurajsuraj@gmail.com
description:       Silent Observations
author:            J
#url:               "localhost:4000"
url:               "http://squarezero.github.io/"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Analytics
analytics:
  provider               : "google-gtag"
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-6HEKBWN946"
    anonymize_ip         : # true, false (default)
